import { filterResourceTags } from "./filterResourceTags";

const resourcesToFilter = [
    {
        id: 114,
        resource_name: "test9",
        author_name: "t",
        url: "w",
        description: "t",
        content_type: "video",
        build_phase: 8,
        date_added: "2023-09-19T07:51:56.292Z",
        recommender_id: 2,
        recommender_comment: "I recommend this resource after having used it",
        recommender_reason: "",
        likes_count: 0,
        dislikes_count: 0,
        tags: ["JavaScript"],
        recommender_name: "Tomasz",
    },
    {
        id: 113,
        resource_name: "test7",
        author_name: "tomasz",
        url: "www.test7.com",
        description: "test7",
        content_type: "reference",
        build_phase: 7,
        date_added: "2023-09-19T07:46:46.499Z",
        recommender_id: 2,
        recommender_comment: "I recommend this resource after having used it",
        recommender_reason: "",
        likes_count: 0,
        dislikes_count: 0,
        tags: ["react"],
        recommender_name: "Tomasz",
    },
    {
        id: 112,
        resource_name: "test6",
        author_name: "tomasz",
        url: "www.test6.com",
        description: "test6",
        content_type: "reference",
        build_phase: 6,
        date_added: "2023-09-18T21:20:37.234Z",
        recommender_id: 2,
        recommender_comment: "I recommend this resource after having used it",
        recommender_reason: "",
        likes_count: 0,
        dislikes_count: 0,
        tags: [""],
        recommender_name: "Tomasz",
    },
    {
        id: 111,
        resource_name: "testing 5",
        author_name: "tomasz",
        url: "www.testing5com",
        description: "testing no 5",
        content_type: "reference",
        build_phase: 5,
        date_added: "2023-09-18T20:16:10.078Z",
        recommender_id: 2,
        recommender_comment: "I recommend this resource after having used it",
        recommender_reason: "",
        likes_count: 0,
        dislikes_count: 0,
        tags: ["react"],
        recommender_name: "Tomasz",
    },
    {
        id: 110,
        resource_name: "testing 4",
        author_name: "tomasz",
        url: "www.testing4.com",
        description: "testing4",
        content_type: "reference",
        build_phase: 4,
        date_added: "2023-09-18T19:37:08.009Z",
        recommender_id: 2,
        recommender_comment: "I recommend this resource after having used it",
        recommender_reason: "",
        likes_count: 0,
        dislikes_count: 0,
        tags: ["html"],
        recommender_name: "Tomasz",
    },
    {
        id: 109,
        resource_name: "testing 3",
        author_name: "tomasz",
        url: "www.testing3.com",
        description: "testing3",
        content_type: "resource list",
        build_phase: 3,
        date_added: "2023-09-18T19:34:49.442Z",
        recommender_id: 2,
        recommender_comment: "I do not recommend this resource, having used it",
        recommender_reason: "",
        likes_count: 0,
        dislikes_count: 0,
        tags: ["react"],
        recommender_name: "Tomasz",
    },
    {
        id: 108,
        resource_name: "testing 2",
        author_name: "tomasz",
        url: "www.testing2.com",
        description: "testing2",
        content_type: "reference",
        build_phase: 2,
        date_added: "2023-09-18T18:26:59.398Z",
        recommender_id: 2,
        recommender_comment: "I recommend this resource after having used it",
        recommender_reason: "",
        likes_count: 0,
        dislikes_count: 0,
        tags: ["react"],
        recommender_name: "Tomasz",
    },
    {
        id: 107,
        resource_name: "testing 1",
        author_name: "none",
        url: "www.nourl.com",
        description: "nothing",
        content_type: "reference",
        build_phase: 1,
        date_added: "2023-09-18T18:24:30.694Z",
        recommender_id: 2,
        recommender_comment: "I do not recommend this resource, having used it",
        recommender_reason: "don't use ",
        likes_count: 0,
        dislikes_count: 0,
        tags: ["javascript"],
        recommender_name: "Tomasz",
    },
    {
        id: 106,
        resource_name: "p5js reference docs",
        author_name: "p5.js",
        url: "https://p5js.org/reference/",
        description: "reference documentation for the p5js library",
        content_type: "reference",
        build_phase: 1,
        date_added: "2023-09-18T18:22:07.987Z",
        recommender_id: 2,
        recommender_comment: "I recommend this resource after having used it",
        recommender_reason: "it's very good for p5js",
        likes_count: 0,
        dislikes_count: 0,
        tags: ["p5js"],
        recommender_name: "Tomasz",
    },
];
const filteredResources = [
    {
        id: 113,
        resource_name: "test7",
        author_name: "tomasz",
        url: "www.test7.com",
        description: "test7",
        content_type: "reference",
        build_phase: 7,
        date_added: "2023-09-19T07:46:46.499Z",
        recommender_id: 2,
        recommender_comment: "I recommend this resource after having used it",
        recommender_reason: "",
        likes_count: 0,
        dislikes_count: 0,
        tags: ["react"],
        recommender_name: "Tomasz",
    },

    {
        id: 111,
        resource_name: "testing 5",
        author_name: "tomasz",
        url: "www.testing5com",
        description: "testing no 5",
        content_type: "reference",
        build_phase: 5,
        date_added: "2023-09-18T20:16:10.078Z",
        recommender_id: 2,
        recommender_comment: "I recommend this resource after having used it",
        recommender_reason: "",
        likes_count: 0,
        dislikes_count: 0,
        tags: ["react"],
        recommender_name: "Tomasz",
    },

    {
        id: 109,
        resource_name: "testing 3",
        author_name: "tomasz",
        url: "www.testing3.com",
        description: "testing3",
        content_type: "resource list",
        build_phase: 3,
        date_added: "2023-09-18T19:34:49.442Z",
        recommender_id: 2,
        recommender_comment: "I do not recommend this resource, having used it",
        recommender_reason: "",
        likes_count: 0,
        dislikes_count: 0,
        tags: ["react"],
        recommender_name: "Tomasz",
    },
    {
        id: 108,
        resource_name: "testing 2",
        author_name: "tomasz",
        url: "www.testing2.com",
        description: "testing2",
        content_type: "reference",
        build_phase: 2,
        date_added: "2023-09-18T18:26:59.398Z",
        recommender_id: 2,
        recommender_comment: "I recommend this resource after having used it",
        recommender_reason: "",
        likes_count: 0,
        dislikes_count: 0,
        tags: ["react"],
        recommender_name: "Tomasz",
    },
];
test("filter resource tages", () => {
    expect(filterResourceTags(["react"], resourcesToFilter)).toStrictEqual(
        filteredResources
    );
});
