import { searchResources } from "./searchResources";
const resourcesToFilter = [
    {
        id: 113,
        resource_name: "test7",
        author_name: "tomasz",
        url: "www.test7.com",
        description: "test7",
        content_type: "reference",
        build_phase: 7,
        date_added: "2023-09-19T07:46:46.499Z",
        recommender_id: 2,
        recommender_comment: "I recommend this resource after having used it",
        recommender_reason: "",
        likes_count: 0,
        dislikes_count: 0,
        tags: ["react"],
        recommender_name: "Tomasz",
    },

    {
        id: 111,
        resource_name: "JavaScript course",
        author_name: "tomasz",
        url: "www.testing5com",
        description: "testing no 5",
        content_type: "reference",
        build_phase: 5,
        date_added: "2023-09-18T20:16:10.078Z",
        recommender_id: 2,
        recommender_comment: "I recommend this resource after having used it",
        recommender_reason: "",
        likes_count: 0,
        dislikes_count: 0,
        tags: ["react"],
        recommender_name: "Tomasz",
    },

    {
        id: 109,
        resource_name: "testing 3",
        author_name: "tomasz",
        url: "www.testing3.com",
        description: "testing3",
        content_type: "resource list",
        build_phase: 3,
        date_added: "2023-09-18T19:34:49.442Z",
        recommender_id: 2,
        recommender_comment: "I do not recommend this resource, having used it",
        recommender_reason: "",
        likes_count: 0,
        dislikes_count: 0,
        tags: ["react"],
        recommender_name: "Tomasz",
    },
    {
        id: 108,
        resource_name: "testing 2",
        author_name: "tomasz",
        url: "www.testing2.com",
        description: "testing2",
        content_type: "reference",
        build_phase: 2,
        date_added: "2023-09-18T18:26:59.398Z",
        recommender_id: 2,
        recommender_comment: "I recommend this resource after having used it",
        recommender_reason: "",
        likes_count: 0,
        dislikes_count: 0,
        tags: ["react"],
        recommender_name: "Tomasz",
    },
];
const filteredResources = [
    {
        id: 111,
        resource_name: "JavaScript course",
        author_name: "tomasz",
        url: "www.testing5com",
        description: "testing no 5",
        content_type: "reference",
        build_phase: 5,
        date_added: "2023-09-18T20:16:10.078Z",
        recommender_id: 2,
        recommender_comment: "I recommend this resource after having used it",
        recommender_reason: "",
        likes_count: 0,
        dislikes_count: 0,
        tags: ["react"],
        recommender_name: "Tomasz",
    },
];
test("filter resource tages", () => {
    expect(searchResources("Java", resourcesToFilter)).toStrictEqual(
        filteredResources
    );
});
